agents:
  name: "Place Search Agent"
  retries: 3
  timeout: 120
  end_strategy: "exhaustive"
  model_name: "gpt-4o-mini"
  max_tokens: 10000
  temperature: 0.7
  top_p: 0.95
  enable_thinking: false
